# Generated by Django 5.1.15 on 2026-02-21 11:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('order', 'Pedido'), ('payment', 'Pago'), ('shipment', 'Envío'), ('catalog', 'Catálogo'), ('other', 'Otro')], max_length=20)),
                ('status', models.CharField(choices=[('received', 'Recibido'), ('queued', 'En cola'), ('processing', 'Procesando'), ('processed', 'Procesado'), ('failed', 'Fallido')], default='received', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channels.channel')),
            ],
            options={
                'verbose_name': 'evento webhook',
                'verbose_name_plural': 'eventos webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
