# Generated by Django 5.1.15 on 2026-02-21 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Ej: mercadolibre, amazon, shopify', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('marketplace', 'Marketplace'), ('ecommerce', 'E-Commerce propio'), ('b2b', 'B2B / Mayorista')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerChannelCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credentials', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_credentials', to='channels.channel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_credentials', to='sellers.seller')),
            ],
            options={
                'unique_together': {('seller', 'channel')},
            },
        ),
    ]
