# Generated by Django 5.1.15 on 2026-02-21 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('oca', 'OCA'), ('andreani', 'Andreani'), ('dhl', 'DHL'), ('correo_argentino', 'Correo Argentino'), ('custom', 'Propio')], max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('tracking_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('ready', 'Listo para retirar'), ('in_transit', 'En tránsito'), ('out_for_delivery', 'En camino'), ('delivered', 'Entregado'), ('failed', 'Entrega fallida'), ('returned', 'Devuelto')], default='pending', max_length=30)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('events', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
            ],
            options={
                'verbose_name': 'envío',
                'verbose_name_plural': 'envíos',
            },
        ),
    ]
