# Generated by Django 5.1.15 on 2026-02-21 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255, verbose_name='Razón social')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='CUIT/RUT')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('active', 'Activo'), ('suspended', 'Suspendido')], default='pending', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de comisión del SC sobre ventas del seller.', max_digits=5)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
            },
        ),
    ]
