# Generated by Django 5.2.11 on 2026-02-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='tenant_id',
            field=models.CharField(help_text='ID único de integración (UUID) para Webhooks', max_length=255, null=True, unique=True),
        ),
    ]
